### PR TITLE
Added an importer for Österbotten events

### PR DESCRIPTION
**Pull request by anttileppa**
Added an importer for Österbotten -events

### CODE REVIEW

**Review by Rikuoja — APPROVED** [review]
Looks sensible to me!

**Review by dankiki — CHANGES_REQUESTED** [review]
please, add tests, that would demonstrate the structure of the imported data.

**Comment by anttileppa** [comment]
@dankiki added basic tests for the importer, is it ok for merging now?

**Review by dankiki — APPROVED** [review]

**Comment by dankiki** [comment]
Hi! I'm sorry for this delay @anttileppa! I've sent you an invitation to slack channel to your metatavu email. Could you please update the branch and squash the commits? Then I'll merge it together with the other PRs of yours.

**Comment by anttileppa** [comment]
@dankiki i received the invitation and accepted it but somehow i cannot access the Slack channel so maybe something went wrong while accepting, could you send another invitation?

**Comment by anttileppa** [comment]
@dankiki branch has been updated to match the upstream. I think that GitHub actually has support for merging PR with squash and merge strategy nowadays

**Comment by anttileppa** [comment]
@dankiki branch has been updated to the upstream and squashed to single commit. Can it be merged now?

**Pull request closed without merging**
