### PR TITLE
LINK-1903 | Upgrade dependencies

### PR DESCRIPTION
**Pull request by harriris-vincit**
### Description
Upgrade several dependencies to their latest versions.

`elasticsearch` has been defined to use versions below 8 so it was not upgraded. Since `urllib3` is a dependency for it, it was not upgraded either to a version that wouldn't work with the project's `elasticsearch` version.

Bumping `wheel` from `0.42.0` to `0.43.0` seems to cause Snyk to think the package is vulnerable and the scan fails, yet the reported vulnerability has to do with much older versions. The scan succeeds if the version is kept at `0.42.0`.

Some code and formatting changes were also needed due to upgrading `djangorestframework` and `black`.
### Closes
[LINK-1903](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1903)

[LINK-1903]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**LINKEDEVENTS-API branch is deployed to platta: https://linkedevents-pr886.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**LINKEDEVENTS-API branch is deployed to platta: https://linkedevents-pr886.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**LINKEDEVENTS-API branch is deployed to platta: https://linkedevents-pr886.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**LINKEDEVENTS-API branch is deployed to platta: https://linkedevents-pr886.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**LINKEDEVENTS-API branch is deployed to platta: https://linkedevents-pr886.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**LINKEDEVENTS-API branch is deployed to platta: https://linkedevents-pr886.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**LINKEDEVENTS-API branch is deployed to platta: https://linkedevents-pr886.api.dev.hel.ninja** :rocket::rocket::rocket:

**Review by nicobav — APPROVED** [review]

**Pull request merged**
