### PR TITLE
LINK-1907 | Add Price Groups for Offers

### PR DESCRIPTION
**Pull request by harriris-vincit**
### Description
Makes it possible to add numeric pricing information for event `Offers`. These can be used to provide initial values for registration pricing groups when creating a registration for the event (UI or API client can do that).
### Closes
[LINK-1907](https://helsinkisolutionoffice.atlassian.net/browse/LINK-1907)

[LINK-1907]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-1907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**LINKEDEVENTS-API branch is deployed to platta: https://linkedevents-pr868.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**LINKEDEVENTS-API branch is deployed to platta: https://linkedevents-pr868.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**LINKEDEVENTS-API branch is deployed to platta: https://linkedevents-pr868.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**LINKEDEVENTS-API branch is deployed to platta: https://linkedevents-pr868.api.dev.hel.ninja** :rocket::rocket::rocket:

**Review by tuomas777 — APPROVED** [review]
Quite a lot of code, but still couldn't spot anything to complain about 😞 

Great job! 👍 🐬

**Pull request merged**
