### PR TITLE
LINK-1534: Change "too long recurring activity" into a warning instead of an error in Harrastushaku

### PR DESCRIPTION
**Pull request by danipran**
While it is an error, it's not really something we can do anything about. So in practice, it's just a warning.

### CODE REVIEW

**Review by charn — CHANGES_REQUESTED** [review]

**Comment by danipran** [comment]
...oops 🤡

**Review by charn — APPROVED** [review]
LGTM! :+1: :shipit:

**Comment by danipran** [comment]
Changing this into a draft, need to discuss this issue further before merging.

**Comment by danipran** [comment]
Obsolete; the lines in question get removed in https://github.com/City-of-Helsinki/linkedevents/pull/769/

**Pull request closed without merging**
