### PR TITLE
Added an importer for Mikkeli Nyt  -events

### PR DESCRIPTION
**Pull request by anttileppa**
Added support for importing events from Mikkeli Nyt

### CODE REVIEW

**Comment by dankiki** [comment]
Hi, Antti! I think that in order to add local importers for the non-Helsinki events and, in general, to use the linkedevents for other municipalities you'd need to fork the project.

**Comment by Rikuoja** [comment]
It's not my decision anymore, but up to now we have accepted external code to the codebase if they are separate modules, so that anybody can use the code :) We don't want to fork the codebase if it is not necessary?

**Comment by dankiki** [comment]
That might be possible as well =) I guess we'd need to discuss this a bit more internally =)

**Review by Rikuoja — APPROVED** [review]
This looks sensible to me, but will not merge as I am not the one who will be responsible for the codebase in the future :) In general, I would recommend accepting separate modules that do no changes to the base codebase, to prevent the codebases of different cities diverging if it can be prevented.

**Comment by dankiki** [comment]
I don't mind adding these modules as well. Only please have some tests showing the structure of the imported data, that would make the code more editable in the future.

**Review by dankiki — CHANGES_REQUESTED** [review]
very sensible, but would be great to see the structure of the imported data. in a test.

**Comment by anttileppa** [comment]
@dankiki added basic tests for importing and removing events, is it ok now or should i add more tests?

**Review by dankiki — APPROVED** [review]
looks good!

**Comment by dankiki** [comment]
Hi! @anttileppa I was thinking you'd merge them yourself, just in case you realize the last minute that you want to add something, but I could of course do that for you as well.
would you like to join a common slack channel for possible discussions?

**Comment by anttileppa** [comment]
@dankiki I would really much like to join the slack channel but I don't think i have permission to merge the PR (it says "Only those with write access to this repository can merge pull requests.")

**Pull request merged**
