### PR TITLE
LINK-2071 | Mandatory maximum attendee capacity

### PR DESCRIPTION
**Pull request by harriris-vincit**
### Description
It has been decided by the city that the maximum attendee capacity information of events and registrations is to be used for statistical purposes to monitor the city's event attendee volumes. It has also been noted that the field type for both the maximum and minimum attendee capacitities, `PositiveSmallIntegerField`, is too small for possible large events where there can be more than 500 thousand attendees.

To address the issues, this PR implements the following:

- Field type for `maximum_attendee_capacity` and `minimum_attendee_capacity` is changed to `PositiveIntegerField` to allow much larger attendee capacity values. This applies to both `Event` and `Registration`.
- `maximum_attendee_capacity` is made mandatory for registrations when they are created or edited through Django admin or the APIs.
- Maximum and minimum attendee capacity fields are added to `EventAdmin` to allow settings values for them there too. The field are **not** mandatory for events as they would be breaking changes.
- Help text telling about the use for statistical purposes is added for `maximum_attendee_capacity` to both `EventAdmin` and `RegistrationAdmin`.

### Closes
[LINK-2071](https://helsinkisolutionoffice.atlassian.net/browse/LINK-2071)

[LINK-2071]: https://helsinkisolutionoffice.atlassian.net/browse/LINK-2071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**LINKEDEVENTS-API branch is deployed to platta: https://linkedevents-pr936.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**LINKEDEVENTS-API branch is deployed to platta: https://linkedevents-pr936.api.dev.hel.ninja** :rocket::rocket::rocket:

**Review by nicobav — APPROVED** [review]
LGTM 👍 

On a minor side note that the commit title could have a scope "registration" e.g  `feat(registration): ...`
So that the when building the changelog registration things (should) get grouped together nicely

**Comment by terovirtanen** [comment]
**LINKEDEVENTS-API branch is deployed to platta: https://linkedevents-pr936.api.dev.hel.ninja** :rocket::rocket::rocket:

**Pull request merged**
