### PR TITLE
LINK-510 LINK-511 event retrieval and tests

### PR DESCRIPTION
**Pull request by dankiki**
Retrieving a list of events by ids. 
Refactor of test_event_get to get rid of repetitive code for improving the readability

### CODE REVIEW

**Review by nikomakela — COMMENTED** [review]
2 tests fails on my machine and I also get a lot of naive datetime error (75 times): `"DateTimeField Event.end_time received a naive datetime (2020-02-19 11:22:32) while time zone support is active."`

```
events/tests/test_event_get.py::test_get_event_list_verify_bbox_filter FAILED
events/tests/test_event_get.py::test_language_filter FAILED
```

Those errors might be related to my database state. The migration files are not in healthy shape 😯 
```
    @pytest.mark.django_db
    def test_language_filter(api_client, event, event2, event3):
        event.name_sv = 'namn'
        event.save()
        event2.in_language.add(Language.objects.get_or_create(id='en')[0])
        event2.in_language.add(Language.objects.get_or_create(id='sv')[0])
        event2.save()
        event3.name_ru = 'название'
        event3.in_language.add(Language.objects.get_or_create(id='et')[0])
        event3.save()

        # Finnish should be the default language
        get_list_and_assert_events('language=fi', [event, event2, event3])

        # Swedish should have two events (matches in_language and name_sv)
        get_list_and_assert_events('language=sv', [event, event2])

        # English should have one event (matches in_language)
        get_list_and_assert_events('language=en', [event2])

        # Russian should have one event (matches name_ru)
>       get_list_and_assert_events('language=ru', [event3])

events/tests/test_event_get.py:415:
```


```
    def assert_events_in_response(events, response, query=''):
        response_event_ids = {event['id'] for event in response.data['data']}
        expected_event_ids = {event.id for event in events}
        if query:
>           assert response_event_ids == expected_event_ids, f'\nquery: {query}'
E           AssertionError:
E             query: bbox=0.00022548446490595173,22.511480090529965,0.0006764538126717188,22.51192804036402
E           assert set() == {'system:test_event'}
E             Extra items in the right set:
E             'system:test_event'
E             Full diff:
E             - {'system:test_event'}
E             + set()
```

**Comment by nikomakela** [comment]
For a naive datetimes I've used this 

```
from django.utils import timezone
def naive_datetime_to_tz_aware(datetime: str) -> str:
    return datetime + "T00:00:00.000Z" if datetime else None
```

```
        start_date = naive_datetime_to_tz_aware(self.request.GET.get("start", None))
        today = datetime.datetime.now(tz=timezone.utc)
```

**Comment by dankiki** [comment]
> For a naive datetimes I've used this
> 
> ```
> from django.utils import timezone
> def naive_datetime_to_tz_aware(datetime: str) -> str:
>     return datetime + "T00:00:00.000Z" if datetime else None
> ```
> 
> ```
>         start_date = naive_datetime_to_tz_aware(self.request.GET.get("start", None))
>         today = datetime.datetime.now(tz=timezone.utc)
> ```
all tests passing and naive datetimes fixed.

**Review by nikomakela — APPROVED** [review]
Code changes are ok and the naive date times are fixed. Cannot verify by running the tests locally at the moment.

**Pull request merged**
