### PR TITLE
build: pipeline upgrade

### PR DESCRIPTION
**Pull request by terovirtanen**
[OH-35](https://helsinkisolutionoffice.atlassian.net/browse/OH-35)

[OH-35]: https://helsinkisolutionoffice.atlassian.net/browse/OH-35?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**LINKEDEVENTS-API branch is deployed to platta: https://linkedevents-pr847.api.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## api tests result is __failed__ for https://linkedevents-pr847.api.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**LINKEDEVENTS-API branch is deployed to platta: https://linkedevents-pr847.api.dev.hel.ninja** :rocket::rocket::rocket:

**Review by danipran — APPROVED** [review]

**Comment by terovirtanen** [comment]
**LINKEDEVENTS-API branch is deployed to platta: https://linkedevents-pr847.api.dev.hel.ninja** :rocket::rocket::rocket:

**Pull request merged**
