### PR TITLE
fix: change Enkora importer date interval and yso mappings

### PR DESCRIPTION
**Pull request by hel-andreasg**
Changes to date interval used for importing places and courses, as well the yso-mappings as required by liikunta.hel.fi. Agreed with KUVA/Liikunta

### CODE REVIEW

**Comment by terovirtanen** [comment]
**LINKEDEVENTS-API branch is deployed to platta: https://linkedevents-pr909.api.dev.hel.ninja** :rocket::rocket::rocket:

**Review by tuomas777 — CHANGES_REQUESTED** [review]
Seems splendid, but apparently there is something that upsets Black:

```
Run black --check .
would reformat /home/runner/work/linkedevents/linkedevents/events/importer/enkora.py

Oh no! 💥 💔 💥
1 file would be reformatted, 398 files would be left unchanged.
```

**Comment by hel-andreasg** [comment]
Should be good to go now from a formatting point of view.

**Comment by terovirtanen** [comment]
**LINKEDEVENTS-API branch is deployed to platta: https://linkedevents-pr909.api.dev.hel.ninja** :rocket::rocket::rocket:

**Review by tuomas777 — APPROVED** [review]
LGTM 👍

**Pull request merged**
